[project]
org-name = "ballerina"
version = "1.0.2"

[dependencies]
"ballerina/io" = "0.5.2"
"ballerina/http" = "1.0.2"
"ballerina/log" = "1.0.2"
"ballerina/stringutils" = "0.5.2"
"ballerina/mime" = "1.0.2"
"ballerina/auth" = "1.0.2"
"ballerina/cache" = "2.0.2"
"ballerina/time" = "1.0.3"
"ballerina/crypto" = "1.0.2"
"ballerina/file" = "0.5.3"
"ballerina/reflect" = "0.5.2"
"ballerina/runtime" = "0.5.2"
"ballerina/system" = "0.6.2"
"ballerina/task" = "1.1.2"

[platform]
target = "java11"

    [[platform.libraries]]
    artifactId = "http"
    version = "1.0.2-SNAPSHOT"
    path = "./lib/http-native-1.0.2-SNAPSHOT.jar"
    groupId = "ballerina"
    modules = ["websocket"]

    [[platform.libraries]]
    artifactId = "websocket"
    version = "1.0.2-SNAPSHOT"
    path = "../websocket-native/build/libs/websocket-native-1.0.2-SNAPSHOT.jar"
    groupId = "ballerina"
    modules = ["websocket"]

    [[platform.libraries]]
    artifactId = "mime-native"
    version = "1.0.2-SNAPSHOT"
    path = "./lib/mime-native-1.0.2-SNAPSHOT.jar"
    groupId = "ballerina"
    modules = ["websocket"]

    [[platform.libraries]]
    artifactId = "netty-common"
    version = "4.1.50.Final"
    path = "./lib/netty-common-4.1.50.Final.jar"
    groupId = "io.netty"
    modules = ["websocket"]

    [[platform.libraries]]
    artifactId = "netty-buffer"
    version = "4.1.50.Final"
    path = "./lib/netty-buffer-4.1.50.Final.jar"
    groupId = "io.netty"
    modules = ["websocket"]

    [[platform.libraries]]
    artifactId = "netty-transport"
    version = "4.1.50.Final"
    path = "./lib/netty-transport-4.1.50.Final.jar"
    groupId = "io.netty"
    modules = ["websocket"]

    [[platform.libraries]]
    artifactId = "netty-resolver"
    version = "4.1.50.Final"
    path = "./lib/netty-resolver-4.1.50.Final.jar"
    groupId = "io.netty"
    modules = ["websocket"]

    [[platform.libraries]]
    artifactId = "netty-handler"
    version = "4.1.50.Final"
    path = "./lib/netty-handler-4.1.50.Final.jar"
    groupId = "io.netty"
    modules = ["websocket"]

    [[platform.libraries]]
    artifactId = "netty-codec-http"
    version = "4.1.50.Final"
    path = "./lib/netty-codec-http-4.1.50.Final.jar"
    groupId = "io.netty"
    modules = ["websocket"]

    [[platform.libraries]]
    artifactId = "netty-codec"
    version = "4.1.50.Final"
    path = "./lib/netty-codec-4.1.50.Final.jar"
    groupId = "io.netty"
    modules = ["websocket"]

    [[platform.libraries]]
    artifactId = "netty-handler-proxy"
    version = "4.1.50.Final"
    path = "./lib/netty-handler-proxy-4.1.50.Final.jar"
    groupId = "io.netty"
    modules = ["websocket"]

    [[platform.libraries]]
    artifactId = "netty-codec-http2"
    version = "4.1.50.Final"
    path = "./lib/netty-codec-http2-4.1.50.Final.jar"
    groupId = "io.netty"
    modules = ["websocket"]

    [[platform.libraries]]
    artifactId = "commons-pool"
    version = "1.5.6.wso2v1"
    path = "./lib/commons-pool-1.5.6.wso2v1.jar"
    groupId = "commons-pool.wso2"
    modules = ["websocket"]

    [[platform.libraries]]
    artifactId = "snakeyaml"
    version = "1.26.0.wso2v1"
    path = "./lib/snakeyaml-1.26.0.wso2v1.jar"
    groupId = "org.wso2.orbit.org.yaml"
    modules = ["websocket"]

    [[platform.libraries]]
    artifactId = "bcprov-jdk15on"
    version = "1.61"
    path = "./lib/bcprov-jdk15on-1.61.jar"
    groupId = "org.bouncycastle"
    modules = ["websocket"]

    [[platform.libraries]]
    artifactId = "bcpkix-jdk15on"
    version = "1.61"
    path = "./lib/bcpkix-jdk15on-1.61.jar"
    groupId = "org.bouncycastle"
    modules = ["websocket"]

    [[platform.libraries]]
    artifactId = "netty-tcnative-boringssl-static"
    version = "2.0.31.Final"
    path = "./lib/netty-tcnative-boringssl-static-2.0.31.Final.jar"
    groupId = "io.netty"
    modules = ["websocket"]

    [[platform.libraries]]
    artifactId = "mimepull"
    version = "1.9.11"
    path = "./lib/mimepull-1.9.11.jar"
    groupId = "org.jvnet.mimepull"
    modules = ["websocket"]
